DROP USER IF EXISTS 'Author'@'localhost';
CREATE USER 'Author'@'localhost' IDENTIFIED BY 'Authorizer';

use LEARNING_TEACHING_ACCOUNT;
GRANT EXECUTE ON PROCEDURE GET_ACCOUNT_ID TO 'Author'@'localhost';
GRANT EXECUTE ON PROCEDURE GET_ACCOUNT_NAME TO 'Author'@'localhost';
GRANT EXECUTE ON PROCEDURE CHANGE_PASSWORD_ACCOUNT TO 'Author'@'localhost';
use Learning_Teaching;
GRANT EXECUTE ON PROCEDURE GET_TYPE_ACCOUNT_ID TO 'Author'@'localhost';
GRANT EXECUTE ON PROCEDURE GET_EMPLOYEE TO 'Author'@'localhost';