drop schema  if exists Learning_Teaching1;
CREATE SCHEMA Learning_Teaching1;

USE Learning_Teaching1;

CREATE TABLE MemberOfEducationUnit(
    ID CHAR(9),
    Gender CHAR,
    Fname NVARCHAR(15) NOT NULL,
    Lname NVARCHAR(30) NOT NULL,
    DOB DATE,
    Email NVARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE Employee(
    EmployeeID CHAR(6),
    PersonalEID CHAR(9) UNIQUE NOT NULL,
    PRIMARY KEY (EmployeeID),
    FOREIGN KEY (PersonalEID) REFERENCES MemberOfEducationUnit(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Student(
    StudentID CHAR(7),
    YearofAdmission YEAR NOT NULL,
    PersonalSID CHAR(9) UNIQUE NOT NULL,
    PRIMARY KEY (StudentID),
    FOREIGN KEY (PersonalSID) REFERENCES MemberOfEducationUnit(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AAOEmployee(
    AEID CHAR(6),
    PRIMARY KEY (AEID),
    FOREIGN KEY (AEID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SeniorLecturer(
    SLID CHAR(6),
    PRIMARY KEY (SLID),
    FOREIGN KEY (SLID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Lecturer(
    LID CHAR(6),
    PRIMARY KEY (LID),
    FOREIGN KEY (LID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Faculty(
    FacultyName NVARCHAR(70),
    PRIMARY KEY (FacultyName)
);

CREATE TABLE `Subject`(
    CID CHAR(6),
    CName NVARCHAR(50) NOT NULL,
    STATUS BOOLEAN,
    NoCredits INT NOT NULL,
    PRIMARY KEY (CID),
    CONSTRAINT subject_1 CHECK (
        NoCredits BETWEEN 1
        AND 3
    )
);
CREATE TABLE Textbook(
    ISBN CHAR(7),
    TName NVARCHAR(50) NOT NULL,
    PRIMARY KEY (ISBN)
);

CREATE TABLE Author(
    AID CHAR(7),
    AName NVARCHAR(50) NOT NULL,
    PRIMARY KEY (AID)
);

CREATE TABLE Publisher(
    PName NVARCHAR(50),
    Location NVARCHAR(80),
    PRIMARY KEY (PName)
);

CREATE TABLE Class(
    `Year` YEAR,
    Semester CHAR(3),
    CCID CHAR(6),
    PRIMARY KEY (`Year`, Semester, CCID),
    FOREIGN KEY (CCID) REFERENCES Subject(CID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE SubClass(
    CYear YEAR,
    CSemester CHAR(3),
    SCID CHAR(6),
    SID CHAR(3),
    PRIMARY KEY (CYear, CSemester, SCID, SID),
    FOREIGN KEY (CYear, CSemester, SCID) REFERENCES Class(`Year`, Semester, CCID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `Week`(
    WYear YEAR,
    WSemester CHAR(3),
    WCID CHAR(6),
    WSID CHAR(3),
    Number INT,
    WLID CHAR(6) NOT NULL,
    PRIMARY KEY (WYear, WSemester, WCID, WSID,Number,WLID),
    FOREIGN KEY (WYear, WSemester, WCID, WSID) REFERENCES SubClass(CYear, CSemester, SCID, SID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (WLID) REFERENCES Lecturer(LID) ON DELETE CASCADE ON UPDATE CASCADE
                   );



CREATE TABLE `Use`(
    UCID CHAR(6),
    UISBN CHAR(7),
    PRIMARY KEY (UCID, UISBN),
    FOREIGN KEY (UCID) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (UISBN) REFERENCES Textbook(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MainlyUse(
    MCID CHAR(6),
    MISBD CHAR(7),
    PRIMARY KEY (MCID, MISBD),
    FOREIGN KEY (MCID) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MISBD) REFERENCES Textbook(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Prerequisite(
    Csuper CHAR(6),
    Csub CHAR(6),
    PRIMARY KEY (Csuper, Csub),
    FOREIGN KEY (Csuper) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Csub) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Parallel(
    Psuper CHAR(6),
    Psub CHAR(6),
    PRIMARY KEY (Psuper, Psub),
    FOREIGN KEY (Psuper) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Psub) REFERENCES `Subject`(CID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Attend(
    AYear YEAR,
    ASemester CHAR(3),
    ACID CHAR(6),
    ASID CHAR(3),
    AStudentID CHAR(7),
    PRIMARY KEY (AYear, ASemester, ACID, ASID, AStudentID),
    FOREIGN KEY (AStudentID) REFERENCES Student(StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (AYear, ASemester, ACID, ASID) REFERENCES SubClass(CYear, CSemester, SCID, SID) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE Written_by(
    WISBN CHAR(7),
    WAID CHAR(7),
    PRIMARY KEY (WISBN, WAID),
    FOREIGN KEY (WAID) REFERENCES Author(AID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WISBN) REFERENCES Textbook(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE
    Employee
ADD
    (FEName NVARCHAR(70));

ALTER TABLE
    Employee
ADD
    FOREIGN KEY (FEName) REFERENCES Faculty(FacultyName) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
    Student
ADD
    (FSName NVARCHAR(70)  NOT NULL);

ALTER TABLE
    Student
ADD
    FOREIGN KEY (FSName) REFERENCES Faculty(FacultyName) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
    `Subject`
ADD
    (FCName NVARCHAR(70) NOT NULL);

ALTER TABLE
    `Subject`
ADD
    FOREIGN KEY (FCName) REFERENCES Faculty(FacultyName) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE
    SubClass
ADD (SCLID CHAR(6) NULL);
ALTER TABLE
    SubClass
ADD
    FOREIGN KEY (SCLID) REFERENCES Lecturer(LID) ON DELETE CASCADE ON UPDATE CASCADE;



ALTER TABLE
    Lecturer
ADD
    (LSLID CHAR(6));

ALTER TABLE
    Lecturer
ADD
    FOREIGN KEY (LSLID) REFERENCES SeniorLecturer(SLID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
    Textbook
ADD
    (TPName NVARCHAR(50) NOT NULL);

ALTER TABLE
    Textbook
ADD
    FOREIGN KEY (TPName) REFERENCES Publisher(PName) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Phone(
    MOEID CHAR(9),
    PhoneNumber CHAR(11),
    PRIMARY KEY (MOEID, PhoneNumber),
    FOREIGN KEY (MOEID) REFERENCES MemberOfEducationUnit(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE `Status`(
    SSID CHAR(7),
    SemesterStatus CHAR(3),
    LearningStatus INT,
    CHECK (
     LearningStatus <= 2
    ),
    PRIMARY KEY (SSID, SemesterStatus, LearningStatus),
    FOREIGN KEY (SSID) REFERENCES Student(StudentID) ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE Category(
    CISBN CHAR(7),
    CategoryName NVARCHAR(15),
    PRIMARY KEY (CISBN, CategoryName),
    FOREIGN KEY (CISBN) REFERENCES Textbook(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PublishingYear(
    PYISBN CHAR(7),
    PYear YEAR,
    PRIMARY KEY (PYISBN, PYear),
    FOREIGN KEY (PYISBN) REFERENCES Textbook(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);
alter table Subject
add column SLID char(6) not null references  Lecturer(LID);


drop database if exists LEARNING_TEACHING_ACCOUNT;
CREATE DATABASE LEARNING_TEACHING_ACCOUNT;
USE  LEARNING_TEACHING_ACCOUNT;
create table Account
(
    USERID   char(9)      not null,
    USERNAME NVARCHAR(100) not null,
    PASSWORD NVARCHAR(100) not null,
    primary key (USERID, USERNAME),
    constraint USERNAME
        unique (USERNAME)
);