USE LEARNING_TEACHING_ACCOUNT;

DROP PROCEDURE IF EXISTS GET_ACCOUNT_ID;
DELIMITER \\
CREATE PROCEDURE GET_ACCOUNT_ID(id char(9))
BEGIN
    select USERID,USERNAME,PASSWORD from Account where Account.USERID=id;

END\\
DELIMITER ;

DROP PROCEDURE IF EXISTS GET_ACCOUNT_NAME;
DELIMITER \\
CREATE PROCEDURE GET_ACCOUNT_NAME(_USERNAME varchar(100))
BEGIN
    select USERID,USERNAME,PASSWORD from Account where Account.USERNAME=_USERNAME;

END\\
DELIMITER ;
DROP PROCEDURE IF EXISTS CHANGE_PASSWORD_ACCOUNT;
DELIMITER \\
CREATE PROCEDURE CHANGE_PASSWORD_ACCOUNT(_USERNAME nvarchar(100), _PASSWORD NVARCHAR(100))
BEGIN

    IF EXISTS(SELECT *
              FROM Account
              WHERE Account.USERNAME=_USERNAME)
    THEN
        UPDATE Account
        SET PASSWORD=_PASSWORD
        WHERE (Account.USERNAME=_USERNAME);
    END IF;

END\\

DELIMITER ;
call CHANGE_PASSWORD_ACCOUNT('lecturer1','12345');
select * from Account where USERNAME='lecturer1'