USE Learning_Teaching1;

DROP VIEW IF EXISTS SUBCLASS_INFO;
CREATE VIEW SUBCLASS_INFO AS
SELECT CID, CYEAR, CSEMESTER, SID, CNAME, NOCREDITS
FROM SUBCLASS, SUBJECT
WHERE SCID = CID;

DELIMITER //
CREATE TRIGGER check_registered_credits AFTER INSERT ON Attend
	FOR EACH ROW
    BEGIN 
		IF (SELECT SUM(NOCREDITS) FROM Attend, SUBCLASS_INFO WHERE (AYEAR, ASEMESTER) = (CYEAR, CSEMESTER) AND ASTUDENTID = NEW.ASTUDENTID) > 18 THEN
        SIGNAL SQLSTATE '45001' SET MESSAGE_TEXT = "One student cannot registerd more than 18 credits in one semester.";
	   END IF;
    END;
//
DELIMITER ;




